DELIMITER $$
CREATE DEFINER=`kubasz`@`%` PROCEDURE `KLASYFIKUJ`(IN `NAZWA_FIRMY` VARCHAR(40), OUT `REZULTAT` VARCHAR(10))
    NO SQL
BEGIN

DECLARE suma INT DEFAULT 0;
SET suma = UDZIELONE_KREDYTY(NAZWA_FIRMY);

IF suma > 8000 THEN
	SET REZULTAT = "rekin";
ELSE
	SET REZULTAT = "plotka";
END IF;

END$$
DELIMITER ;





DELIMITER $$
CREATE DEFINER=`kubasz`@`%` PROCEDURE `UDZIELONE_POZYCZKI`(IN `nazwa_firmy` VARCHAR(40), OUT `SUMA_POZYCZEK` INT)
    NO SQL
BEGIN
  SELECT SUM(POZYCZKI.kwota) INTO SUMA_POZYCZEK
  FROM POZYCZKI
  WHERE POZYCZKI.firma = nazwa_firmy;
END$$
DELIMITER ;





DELIMITER $$
CREATE DEFINER=`kubasz`@`%` FUNCTION `OPROCENTOWANIE`(`KWOTA_POZYCZKI` INT, `OKRES_SPLATY` INT) RETURNS decimal(3,1)
    NO SQL
BEGIN

IF KWOTA_POZYCZKI <= 1000 THEN
	IF OKRES_SPLATY <= 12 THEN
    	RETURN(10.0);
    ELSEIF OKRES_SPLATY <= 36 THEN
    	RETURN(9.0);
    ELSE
    	RETURN(8.5);
    END IF;
ELSEIF KWOTA_POZYCZKI <= 2000 THEN
	IF OKRES_SPLATY <= 12 THEN
    	RETURN(9.5);
    ELSEIF OKRES_SPLATY <= 36 THEN
    	RETURN(8.0);
    ELSE
    	RETURN(7.0);
    END IF;
END IF;

END$$
DELIMITER ;





DELIMITER $$
CREATE DEFINER=`kubasz`@`%` FUNCTION `UDZIELONE_KREDYTY`(`nazwa_firmy` VARCHAR(40)) RETURNS int
    NO SQL
BEGIN

DECLARE suma INT DEFAULT 0;

SELECT SUM(POZYCZKI.kwota) INTO suma
FROM POZYCZKI
WHERE POZYCZKI.firma = nazwa_firmy;

RETURN(suma);

END$$
DELIMITER ;





DELIMITER $$
CREATE DEFINER=`kubasz`@`%` PROCEDURE `NOWA_POZYCZKA`(IN `ID_KLIENTA` INT, IN `FIRMA` VARCHAR(40), IN `KWOTA` INT, IN `OKRES_SPLATY` INT)
    NO SQL
BEGIN

DECLARE id INT DEFAULT 0;
DECLARE procent DECIMAL(3,1);

SELECT MAX(id_pozyczki) INTO id FROM POZYCZKI;
SET procent = OPROCENTOWANIE(KWOTA, OKRES_SPLATY);

INSERT INTO POZYCZKI(id_pozyczki, id_klienta, firma, kwota, okres_splaty, oprocentowanie) VALUES (id+1, ID_KLIENTA, FIRMA, KWOTA, OKRES_SPLATY, procent);

END$$
DELIMITER ;
